#!/bin/bash

# Wesley T. Honeycutt
# Converts .ai files to .dxf files by way of a temporary .svg and .eps file.
# Requires:
#   Inkscape
#   Pstoedit
# Both of which are available in apt


# License:
# The MIT License (MIT)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

function ai2svg() {
    if test $# -lt 1 ; then
    echo "Pass filename" ; return
  fi
  
  svg=${1%.*}.ai
  echo "inkscape -f $1 -l $svg"
  inkscape -f "$1" -l "$svg"
}

function svg2eps()
{
  if test $# -lt 1 ; then
    echo "Pass filename" ; return
  fi

  eps=${1%.*}.eps

  ai2svg "$1"
  echo "inkscape -f $1 -E $eps"
  inkscape -f "$1" -E "$eps" &> /dev/null
}

function svg2dxf()
{
  if test $# -lt 1 ; then
    echo "Pass filename" ; return
  fi

  base=${1%.*}
  eps=${base}.eps
  dxf=${base}.dxf

  svg2eps "$1"
  echo "pstoedit -dt -f 'dxf:-polyaslines -mm' ${eps} ${dxf}"
  pstoedit -dt -f 'dxf:-polyaslines -mm' "${eps}" "${dxf}" &> /dev/null
  rm "$eps"
}

# Check if everything is installed
command -v inkscape >/dev/null 2>&1 || { echo >&2 "ERROR: This requires inkscape, but it's not found.  Is it installed?"; exit 1; }
command -v pstoedit >/dev/null 2>&1 || { echo >&2 "ERROR: This requires pstoedit, but it's not found.  Is it installed?"; exit 1; }

# Call the ultimate function
# If you want an SVG for some reason, just substitute the function here.
svg2dxf "$1"
